name: Dockerize

on: 
  push:
    branches: 
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: (GITHUB) Checkout repository code
        uses: actions/checkout@v4

      - name: (DOCKER) Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: (DOCKER) Set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host

      - name: (DOCKER) Cache layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: (DOCKER) Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: (DOCKER) Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repo_name }}:latest
            ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repo_name }}:${{ github.sha }}
            ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repo_name }}:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64/v8
          cache-from: "type=local,src=/tmp/.buildx-cache"
          cache-to: "type=local,dest=/tmp/.buildx-cache,mode=max"

      - name: (TRIVY) Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.dockerhub_username }}/${{ secrets.dockerhub_repo_name }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
